package su.msk.nlx2.challengebot.bot;

public enum AdminFlowStep {
    ADD_ADMIN_AWAIT_USER,
    CREATE_CHALLENGE_AWAIT_CHAT,
    CREATE_CHALLENGE_AWAIT_START_DATE,
    CREATE_CHALLENGE_AWAIT_DAYS_TOTAL,
    CREATE_CHALLENGE_AWAIT_POST_TIME,
    CREATE_CHALLENGE_AWAIT_TIMEZONE,
    CREATE_CHALLENGE_AWAIT_EXERCISES_PER_DAY,
    CREATE_CHALLENGE_AWAIT_GROUPS_PER_DAY,
    CREATE_CHALLENGE_AWAIT_CONFIRMATION
}
