package su.msk.nlx2.challengebot.model.type;

public enum ConversationStep {
    AWAIT_MAX_PULL_UPS,
    AWAIT_REMINDER_TIME,
    AWAIT_EXERCISE_CSV,
    ADD_ADMIN_AWAIT_USER,
    CREATE_CHALLENGE_AWAIT_CHAT,
    CREATE_CHALLENGE_AWAIT_DAYS_TOTAL,
    CREATE_CHALLENGE_AWAIT_POST_TIME,
    CREATE_CHALLENGE_AWAIT_TIMEZONE,
    CREATE_CHALLENGE_AWAIT_EXERCISES_PER_DAY,
    CREATE_CHALLENGE_AWAIT_TYPES_PER_DAY,
    CREATE_CHALLENGE_AWAIT_REST_DAY_FREQUENCY,
    CREATE_CHALLENGE_AWAIT_CONFIRMATION
}
